### ISSUE TITLE
Feature Request: Support for webm videos

### ISSUE THREAD

**Issue by carlaKC** [bitcointranscripts/tstbtc#119]
A lot of bitcoin calls take place on jitis, which exports recordings in `webm` format. 

To use `tstbtc` to transcribe these videos, you first have to use [FFmpeg](https://github.com/FFmpeg/FFmpeg) to convert the file (`ffmpep -i video.webm audio.mp3`) and then create the transcript from the audio file. 

It would be great to have this conversion step built if if a `webm` video is provided as a source.

**Comment by adamjonas** [comment]
Concept ack

**Comment by kouloumos** [comment]
Support for `webm` videos has been added.

Note: If you plan to pull the latest version in order to use this new feature, have in mind that the tool had several changes in the last month and it might need to re-install to work properly. Check the README for updated usage examples.

**Comment by carlaKC** [comment]
Running into some issues with this: 

```
tstbtc transcribe "/Users/carla/Downloads/lnspec-2024-01-15.webm" --deepgram --diarize  --loc lightning-specification  --noqueue -t 'Lightning Specification Meeting' -d '2024-01-15' -T 'lightning' -C -D -M -p

Traceback (most recent call last):
  File "/Users/carla/Work/bitcointranscripts/tstbtc/venv/bin/tstbtc", line 5, in <module>
    from transcriber import cli
  File "/Users/carla/Work/bitcointranscripts/tstbtc/venv/lib/python3.11/site-packages/transcriber.py", line 14, in <module>
    from app.commands import queue
ModuleNotFoundError: No module named 'app.commands'
```

Python 3.9.6
pip 23.3.2
2ad1c25

**Comment by kouloumos** [comment]
@carlaKC  I've just pushed an update to the `main` branch (commit: 8949710e1c65099ddbc3179e3c1ed3e7a6f31e0f). Can you please give it a try with the latest changes?

Although this shouldn't be an issue for Python versions > 3.3, if the problem persists, could you try cloning the repo again? Since you're one of the first to run the tool in its current form, there might be OS or version-specific quirks. Please keep me updated, and I'll do my best to address any issues that arise.

Additionally, once you've resolved the current issue, please note that the flags `-C -D -M -p` are not necessary. Just a heads up!

Thanks again for your help, and let me know how it goes!

**Comment by carlaKC** [comment]
Thanks for the quick fix! 

Ran the following on 8949710 and successfully transcribed from webm:
`tstbtc transcribe "/Users/carla/Downloads/lnspec-2024-01-15.webm" --deepgram --diarize  --loc lightning-specification  --noqueue -t 'Lightning Specification Meeting' -d '2024-01-15' -T 'lightning' --github`

I do get a warning, but otherwise all in order :D
```
/Users/carla/Work/bitcointranscripts/tstbtc/venv/lib/python3.11/site-packages/whisper/timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
```
